src/Entity/PanierItem.php
<?php

namespace App\Entity;

use App\Repository\PanierItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierItemRepository::class)]
class PanierItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'panierItems')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Panier $Panier = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Livre $Livre = null;

    #[ORM\Column]
    private ?int $quantity = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPanier(): ?Panier
    {
        return $this->Panier;
    }

    public function setPanier(?Panier $Panier): self
    {
        $this->Panier = $Panier;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->Livre;
    }

    public function setLivre(?Livre $Livre): self
    {
        $this->Livre = $Livre;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

templates/components/footer.html.twig
<footer class="footer">
    <div class="footer_container">
        <div class="footer_about">
            <h3>ABOUT US</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis inventore necessitatibus molestias vel voluptatum! Aperiam libero repudiandae corrupti itaque beatae magni quidem qui odit ea? Doloribus molestias omnis tenetur quod!</p>
            <a href="{{ path('index') }}"><img class="header_logo" src="{{ asset('img/wepik-logo-light.png') }}" alt="librarie logo"></a>
        </div>
        <div>
            <h3>QUICK LINKS</h3>
            <ul class="footer_list">
                <li><a href="">Account</a></li>
                <li><a href="">Livres</a></li>
                <li><a href="">Panier</a></li>
                <li><a href="">Contact us</a></li>
            </ul>
        </div>
        <div>
            <h3>SUPPORT</h3>
            <ul class="footer_list">
                <li><a href="">Tech support</a></li>
                <li><a href="">Documentation</a></li>
                <li><a href="">F.A.Q</a></li>
            </ul>
        </div>
        <div>
            <h3>FOLLOW US</h3>
            <div class="footer_social_wrapper">
                <div class="footer_social"><i class="fa-brands fa-facebook-f"></i></div>
                <div class="footer_social"><i class="fa-brands fa-twitter"></i></div>
                <div class="footer_social"><i class="fa-brands fa-instagram"></i></div>
                <div class="footer_social"><i class="fa-brands fa-youtube"></i></div>
            </div>
        </div>
    </div>
    <div>
        <ul class="footer_list footer_law">
            <li><a href="">Privacy </a>|</li>
            <li><a href="">&nbsp;Terms & Conditions </a>|</li>
            <li><a href="">&nbsp;Cookies</a></li>
        </ul>
    </div>
</footer>

templates/components/header.html.twig
<header class="header">
    <div>
        <a href="{{ path('index') }}"><img class="header_logo" src="{{ asset('img/wepik-logo.png') }}" alt="librarie logo"></a>
    </div>
    <nav class="nav">
        <ul class="nav_list">
            <li><a href="{{ path('index') }}">Home</a></li>
            <li><a href="{{ path('app_livre_index') }}">Livres</a></li>
            <li class="nav_list_panier">
                <a href="{{ path('app_panier')}}"><i class="fa-solid fa-cart-shopping"></i></a>
                {% if app.user %}
                    <div class="list_panier_count">
                        {{app.user.panier.panierItems|length}}
                    </div>
                {% endif %}
                
            </li>
            {% if app.user %}
            <li class="login_btn logged_drop"><a href="{{ path('app_account') }}">{{app.user.nom}}</a></li>
            {% else %}
            <li class="login_btn"><a href="{{ path('app_login') }}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</header>